project:
  type: website

execute:
  freeze: auto

website:
  title: "small tRifles"
  description: "Głupotki"
  site-url: http://www.sapijaszko.net/glupotki/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gsapijaszko
      - icon: mastodon
        href: "https://fosstodon.org/@gsapijaszko"
      - icon: rss
        href: index.xml
      - text: "{{< fa r >}}"
        href: https://www.r-bloggers.com
#  twitter-card: true
format:
  html:
    theme: flatly
    css: styles.css

comments:
  giscus: 
    repo: gsapijaszko/quarto
 
  hypothesis: true
